import * as THREE from 'three';import {OrbitControls} from './vendor/OrbitControls.js';
import {DEFAULTS,LIMITS,derive,constrainWalk} from './model-spec.mjs';import {buildModel} from './model-builder.mjs';import {disposeGroup} from './drawing.mjs';
const $=s=>document.querySelector(s),host=$('#canvas-host'),status=$('#edit-status');
const labels={anchorA:'Anchor A / sq ft',market:'Central market / sq ft',anchorB:'Anchor B / sq ft',depth:'Building depth / ft',wallHeight:'Wall height / ft',ridgeHeight:'Roof ridge height / ft',promenadeLength:'Promenade length / ft',promenadeWidth:'Promenade width / ft',canopyDepth:'Outside canopy depth / ft'};
let model=derive(),built,renderer,controls,scene,camera,view='overall',mode='orbit',yaw=Math.PI,pitch=0,keys=new Set(),last=0,drag=null,hold=null,dirty=true,renderCount=0;
function fields(){const f=$('#fields');f.replaceChildren();for(const [k,v] of Object.entries(model.parameters)){const label=document.createElement('label');label.textContent=`${labels[k]} (${LIMITS[k][0].toLocaleString()}–${LIMITS[k][1].toLocaleString()})`;const input=document.createElement('input');input.name=k;input.type='number';input.step='1';input.min=LIMITS[k][0];input.max=LIMITS[k][1];input.required=true;input.value=v;label.append(input);f.append(label);}}
function openingParameters(){return Object.keys(DEFAULTS).every(k=>model.parameters[k]===DEFAULTS[k]);}
function updateSummary(){ $('#model-state').textContent=openingParameters()?'Opening 120,000 sq ft concept':'Edited concept · '+model.totalArea.toLocaleString('en-CA')+' sq ft · save settings to keep changes'; $('#total-area').textContent=model.totalArea.toLocaleString('en-CA');$('#allocation').textContent=model.zones.map(z=>z.area.toLocaleString('en-CA')).join(' / ');}
function rebuild(p){const next=derive(p);const nextBuilt=buildModel(next);if(built){scene.remove(built.root);disposeGroup(built.root);}model=next;built=nextBuilt;scene.add(built.root);updateSummary();fields();setView('overall');status.textContent=[model.programmeWarning,model.narrowLaneWarning].filter(Boolean).join(' ')||(openingParameters()?'Opening concept applied. Heights and site layout remain illustrative.':'Edited proportions applied. Areas still match the opening programme; save settings to keep your changes.');}
function fitSite(v){if(!['overall','top','road'].includes(v))return;const bounds=new THREE.Box3().setFromObject(built.root),sphere=bounds.getBoundingSphere(new THREE.Sphere()),half=THREE.MathUtils.degToRad(camera.fov/2),angle=Math.min(half,Math.atan(Math.tan(half)*camera.aspect)),direction=(v==='top'?new THREE.Vector3(0,1,.001):v==='road'?new THREE.Vector3(0,.24,1):new THREE.Vector3(1,.85,1.15)).normalize();controls.target.copy(sphere.center);let lo=sphere.radius*.5,hi=sphere.radius/Math.sin(angle)*1.1;const corners=[];for(const x of [bounds.min.x,bounds.max.x])for(const y of [bounds.min.y,bounds.max.y])for(const z of [bounds.min.z,bounds.max.z])corners.push(new THREE.Vector3(x,y,z));for(let i=0;i<24;i++){const d=(lo+hi)/2;camera.position.copy(sphere.center).addScaledVector(direction,d);camera.lookAt(sphere.center);camera.updateMatrixWorld();const fits=corners.every(c=>{const p=c.clone().project(camera);return Math.abs(p.x)<.9&&Math.abs(p.y)<.9&&p.z<1&&p.z>-1;});if(fits)hi=d;else lo=d;}camera.position.copy(sphere.center).addScaledVector(direction,hi);const damping=controls.enableDamping;controls.enableDamping=false;controls.update();controls.enableDamping=damping;}

function syncWalkPad(){host.style.bottom=mode==='walk'&&matchMedia('(max-width:760px)').matches?`${$('#mobile-walk').getBoundingClientRect().height}px`:'0px';}
function setView(v){view=v;keys.clear();hold=null;mode=['promenade','hall'].includes(v)?'walk':'orbit';$('#walk-controls').hidden=mode!=='walk';$('#mobile-walk').hidden=mode!=='walk';$('#viewer').classList.toggle('walking',mode==='walk');syncWalkPad();$('#controls-help').hidden=mode==='walk';$('#auto').checked=false;controls.autoRotate=false;controls.enabled=mode==='orbit';$('#cutaway').checked=false;built.roofs.visible=true;
 let pos,target;const W=model.width,D=model.depth,X=model.marketX,L=model.promenade.length;
 const views={overall:[[W*.8,W*.65,D/2+L*1.5],[0,15,L*.3]],road:[[X,48,model.roadZ+135],[X,24,0]],top:[[0,W*1.05,L*.35+.01],[0,0,L*.35]],rear:[[W*.4,W*.28,-D-180],[0,18,0]],a:[[-W/2-220,65,80],[-W/2,18,0]],b:[[W/2+220,65,80],[W/2,18,0]],promenade:[[X,5.7,model.promenade.endZ-5],[X,5.7,0]],hall:[[X,5.7,D/2-18],[X,5.7,-D/2]]};[pos,target]=views[v];camera.position.set(...pos);controls.target.set(...target);camera.up.set(0,1,0);controls.minDistance=12;controls.maxDistance=Math.max(2000,W*4);controls.maxPolarAngle=Math.PI*.49;camera.near=mode==='walk'?.2:1;camera.far=Math.max(5000,W*8);camera.updateProjectionMatrix();$('#zoom-in').disabled=mode==='walk';$('#zoom-out').disabled=mode==='walk';$('#auto').disabled=mode==='walk';if(mode==='walk'){yaw=Math.PI;pitch=0;look();$('#viewer').focus();}else{controls.update();fitSite(v);}$('#view-note').textContent=({overall:'Whole-site pencil study',road:'Road arrival',top:'Roof and site plan',rear:'Rear market canopy',a:'Anchor A bookend',b:'Anchor B bookend',promenade:'Promenade walk',hall:'Inside the hall'})[v];document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===v)));}
function look(){dirty=true;camera.lookAt(camera.position.x+Math.sin(yaw)*Math.cos(pitch),camera.position.y+Math.sin(pitch),camera.position.z+Math.cos(yaw)*Math.cos(pitch));}
function step(kind,d=4){const angle=yaw+({forward:0,back:Math.PI,left:Math.PI/2,right:-Math.PI/2})[kind];const next=constrainWalk(camera.position.x+Math.sin(angle)*d,camera.position.z+Math.cos(angle)*d,model,{x:camera.position.x,z:camera.position.z});camera.position.set(next.x,5.7,next.z);look();}
function zoom(f){if(mode==='walk')return;const d=camera.position.clone().sub(controls.target).multiplyScalar(f);const dist=d.length();d.multiplyScalar(Math.min(controls.maxDistance,Math.max(controls.minDistance,dist))/dist);camera.position.copy(controls.target).add(d);controls.update();}
function download(name,obj){const u=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
fields();updateSummary();
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0xf0ede4);host.append(renderer.domElement);scene=new THREE.Scene();scene.add(new THREE.AmbientLight(0xffffff,2));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(-120,260,180);scene.add(light);camera=new THREE.PerspectiveCamera(46,1,.1,5000);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.1;controls.screenSpacePanning=true;controls.addEventListener('change',()=>dirty=true);
 rebuild(DEFAULTS);const resize=()=>{const b=host.getBoundingClientRect();renderer.setSize(b.width,b.height,false);camera.aspect=b.width/b.height;camera.updateProjectionMatrix();dirty=true;fitSite(view);};new ResizeObserver(resize).observe(host);new ResizeObserver(syncWalkPad).observe($('#mobile-walk'));resize();$('#loading').hidden=true;
 window.modelApi={ready:true,state:()=>{let meshCount=0;built.root.traverse(o=>{if(o.isMesh)meshCount++;});camera.updateMatrixWorld();const bounds=new THREE.Box3().setFromObject(built.root),projected=[];for(const x of [bounds.min.x,bounds.max.x])for(const y of [bounds.min.y,bounds.max.y])for(const z of [bounds.min.z,bounds.max.z])projected.push(new THREE.Vector3(x,y,z).project(camera).toArray());const canopyPosts=[];built.root.updateMatrixWorld(true);built.root.traverse(o=>{if(o.userData.canopyPostFace)canopyPosts.push({face:o.userData.canopyPostFace,position:o.getWorldPosition(new THREE.Vector3()).toArray()});});return {renderCount,target:controls.target.toArray(),canopyPosts,geometryCount:renderer.info.memory.geometries,projected,view,mode,totalArea:model.totalArea,mezzanine:model.mezzanine,promenadeLength:model.promenade.length,camera:camera.position.toArray(),yaw,distance:camera.position.distanceTo(controls.target),roofVisible:built.roofs.visible,meshCount,crossoverStallPositions:built.root.userData.crossoverStallPositions,crossoverColumnPositions:built.root.userData.crossoverColumnPositions,parameters:model.parameters};}};
 const frame=t=>{const dt=Math.min((t-last)/1000,.05);last=t;if(mode==='walk'){if(keys.has('q')){yaw+=dt*.9;look();}if(keys.has('e')){yaw-=dt*.9;look();}if(hold&&t-hold.started>250)step(hold.kind,dt*6);for(const [codes,kind] of [[['w','ArrowUp'],'forward'],[['s','ArrowDown'],'back'],[['a','ArrowLeft'],'left'],[['d','ArrowRight'],'right']])if(codes.some(c=>keys.has(c)))step(kind,dt*6);}else controls.update();if(dirty&&!document.hidden){renderer.render(scene,camera);renderCount++;dirty=false;}requestAnimationFrame(frame);};requestAnimationFrame(frame);
 document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$('#cutaway').addEventListener('change',e=>{built.roofs.visible=!e.target.checked;dirty=true;});$('#auto').addEventListener('change',e=>{if(mode==='walk'){e.target.checked=false;return;}controls.autoRotate=e.target.checked;controls.autoRotateSpeed=.5;});document.querySelectorAll('[data-leave-walk]').forEach(b=>b.addEventListener('click',()=>setView('overall')));document.querySelectorAll('[data-step]').forEach(b=>{b.addEventListener('contextmenu',e=>e.preventDefault());b.addEventListener('click',()=>{if(Number(b.dataset.suppressUntil||0)<performance.now())step(b.dataset.step);});b.addEventListener('pointerdown',e=>{if(e.button!==0)return;hold={kind:b.dataset.step,started:performance.now()};b.setPointerCapture(e.pointerId);});const release=()=>{if(hold&&performance.now()-hold.started>250)b.dataset.suppressUntil=performance.now()+1000;hold=null;};b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release);});document.querySelectorAll('[data-turn]').forEach(b=>b.addEventListener('click',()=>{yaw+=(b.dataset.turn==='left'?1:-1)*Math.PI/6;look();$('#viewer').focus({preventScroll:true});}));$('#zoom-in').addEventListener('click',()=>zoom(.8));$('#zoom-out').addEventListener('click',()=>zoom(1.25));
 const c=renderer.domElement;c.addEventListener('pointerdown',e=>{if(mode!=='walk')return;drag={x:e.clientX,y:e.clientY,id:e.pointerId};c.setPointerCapture(e.pointerId);});c.addEventListener('pointermove',e=>{if(!drag||mode!=='walk')return;yaw-=(e.clientX-drag.x)*.006;pitch=Math.max(-.65,Math.min(.65,pitch-(e.clientY-drag.y)*.006));drag.x=e.clientX;drag.y=e.clientY;look();});c.addEventListener('pointerup',()=>drag=null);c.addEventListener('pointercancel',()=>drag=null);
 $('#viewer').addEventListener('keydown',e=>{const key=e.key.length===1?e.key.toLowerCase():e.key;if(mode==='walk'&&['w','a','s','d','q','e','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(key)){keys.add(key);e.preventDefault();}});document.addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));window.addEventListener('blur',()=>{keys.clear();hold=null;});document.addEventListener('visibilitychange',()=>{keys.clear();hold=null;});
 $('#model-form').addEventListener('submit',e=>{e.preventDefault();try{const p=Object.fromEntries([...new FormData(e.target)].map(([k,v])=>[k,Number(v)]));rebuild(p);}catch(err){status.textContent=err.message;}});$('#reset').addEventListener('click',()=>rebuild(DEFAULTS));$('#save-settings').addEventListener('click',()=>download('Stony-Plain-pencil-settings.json',{version:'pencil-3d-v1',parameters:model.parameters,assumptions:model.assumptions}));$('#save-model').addEventListener('click',()=>download('Stony-Plain-pencil-scene.json',built.root.toJSON()));$('#load-settings').addEventListener('change',async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>100000)throw new Error('Settings file is too large.');const obj=JSON.parse(await f.text());if(obj.version!=='pencil-3d-v1'||!obj.parameters)throw new Error('Choose a pencil-3d-v1 settings file.');rebuild(obj.parameters);}catch(err){status.textContent=`Could not load settings: ${err.message}`;}finally{e.target.value='';}});
}catch(err){$('#loading').hidden=true;$('#fallback').hidden=false;status.textContent='3D graphics unavailable. Reference drawing remains available.';document.querySelectorAll('aside button,aside input').forEach(b=>b.disabled=true);console.error(err);}
